config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "posts#index"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :users, only: [:show]
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 150 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count

  validate :my_post_cannot_like
  validates :user_id, uniqueness: {
    scope: :post_id,
    message: "は同じ投稿に2回以上いいねはできません"
  }

  private

  def my_post_cannot_like
    errors.add(:base, "自分の投稿にいいねはできません") if user_id == post.user_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :content, presence: true
  validates :ward_id, presence: true
  mount_uploader :img, ImageUploader

  DEFALULATE = 0.0

  def liked_by?(user)
    likes.any? { |like| like.user_id == user.id }
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :ward
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  validates :name, presence: true
  enum gender: { man: 1, woman: 2}
  mount_uploader :img, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/models/ward.rb
class Ward < ActiveHash::Base
  self.data = [
    { id: 1, name: "千代田区" }, { id: 2, name: "中央区" }, { id: 3, name: "港区" },
    { id: 4, name: "新宿区" }, { id: 5, name: "文京区" }, { id: 6, name: "台東区" },
    { id: 7, name: "墨田区" }, { id: 8, name: "墨田区" }, { id: 9, name: "品川区" },
    { id: 10, name: "目黒区" }, { id: 11, name: "大田区" }, { id: 12, name: "世田谷区" },
    { id: 13, name: "渋谷区" }, { id: 14, name: "中野区" }, { id: 15, name: "杉並区" },
    { id: 16, name: "豊島区" }, { id: 17, name: "北区" }, { id: 18, name: "荒川区" },
    { id: 19, name: "板橋区" }, { id: 20, name: "練馬区" }, { id: 21, name: "足立区" },
    { id: 22, name: "葛飾区" }, { id: 23, name: "江戸川区" }, 
  ]

 include ActiveHash::Associations
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :introduction, :img])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :gender, :introduction, :img])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @post, notice: "コメントを書き込みました。"
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post, notice: "コメントを削除しました。"
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user.likes.create!(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end

  def destroy
    current_user.likes.find_by(post_id: params[:post_id]).destroy!
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.includes(:user, :likes, :comments).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to @post, notice: "投稿しました!!"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user, :post).order(created_at: :desc)
  end

  def edit

  end

  def update
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy!
    redirect_to @post
  end

  private

  def post_params
    params.require(:post).permit(:content, :name, :URL, :TEL, :address, :ward_id, :img, :user_id)
  end

  def set_post
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません" if @post.nil?
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーは削除できません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    # ゲストアカウントでログイン
    sign_in User.guest
    # トップページへリダイレクト
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, { only: [:index, :show] }
  PER_PAGE = 9

  def index
    @users = User.where.not(id: current_user.id).page(params[:page]).per(5).order("created_at DESC")
  end

  def show
    @posts = Post.where(user_id: @user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"

  def text_url_to_link(text)
    URI.extract(text, ["http", "https"]).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

      text.gsub!(url, sub_text)
    end

    return text
  end

  def max_width
    if devise_controller?
      "mw-md"
    else
      "mw-xl"
    end
  end
end

app/views/comments/_form.html.erb
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="comment_form">
  <%= form_with(model: [post, comment], url: post_comments_path(@post)) do |f| %>
    <%= f.text_area :content, class: "form-control" %>
    <div class="button-group">
      <%= f.submit "送信", class: "btn comment-submit w-30 mt-2" %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class='comment-counter'>
  <%= comments.count %>件のコメント
</div>
<% comments.each do |comment| %>
  <div class="card-comments mb-1">
    <div class="comment-container">
      <div class="comment-user">
        <p class='text-muted pl-2 pt-1 mb-1'><%=comment.user.name%></p>
      </div>
      <div class="comment-content p-3">
        <%= comment.content %>
      </div>
      <div class='comment_destroy'>
        <% if comment.user == current_user %>
          <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete,data: { confirm: '削除しますか?', remote: true } do %>
            <i class="fas fa-trash" style="color: black;"></i> 削除
          <% end %>
        <% end %>
      </div>
    </div>
    <span class="comment-date pull-right">
      <i class='fas fa-clock home-icon'></i> <%= time_ago_in_words(comment.created_at) %>前
    </span>
  </div>
<% end %>

app/views/comments/index.js.erb
$('#comments_area').html("<%= escape_javascript(render 'index', comments: @comments, post: @post) %>")
$("textarea").val('')

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">x</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #dbb57f;">
  <span class="navbar-brand font-weight-bold">
    <i class="fas fa-tint"></i>
    <%= link_to "Pilates App", class:"text-decoration-none" ,:style=>"color:black;" %>
  </span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active font-weight-bold"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" },class: "nav-item nav-link active font-weight-bold" %>
        <%= link_to "一覧ページ", root_path, class: "nav-item nav-link active font-weight-bold" %>
        <%= link_to "マイページ", user_path(current_user) ,class: "nav-item nav-link active font-weight-bold"%>
        <%= link_to "新規投稿", new_post_path, class: "nav-item nav-link active font-weight-bold" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active font-weight-bold" %>
        <%= link_to "アカウント登録", new_user_registration_path, class: "nav-item nav-link active font-weight-bold" %>
        <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active font-weight-bold" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PilatesAppPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/like", post: @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("posts/dislike", post: @post) %>'

app/views/posts/_dislike.html.erb
<%# 「いいね」していない（クリックすると「いいね！」にする） %>
<%= link_to post_likes_path(post), {method: :post, remote: true, class: "dislike-heart"} do %>
  <i class="far fa-heart"></i>
<% end %>
<%= post.likes_count %>

app/views/posts/_form.html.erb
<div class="form-page">
  <%= form_with model: @post, local: true do |form| %>
    <div class="form-group">
      <%= form.label :name, "店舗名" %>
      <%= form.text_field :name, autofocus: true, class: "form-control" %>
    </div>
    <div class=form-group>
      <%= form.label :ward_id, "エリア" %>
      <%= form.collection_select :ward_id, Ward.all, :id, :name, {include_blank: "選択して下さい"}, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= form.label :address, "住所" %>
      <%= form.text_field :address, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :URL, "URL" %>
      <%= form.url_field :URL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :TEL, "電話番号" %>
      <%= form.text_field :TEL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :content, "投稿者コメント" %>
      <%= form.text_field :content, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.file_field :img, accept: "image/png,image/jpeg,image/gif" %>
    </div>
    <hr>
    <div class="search-button mt-4">
      <%= form.submit "投稿", class: "btn btn-block" %>
    </div>
  <% end %>
</div>

app/views/posts/_like.html.erb
<%# 「いいね！」済み（クリックすると「いいね」解除） %>
<%= link_to post_likes_path(post), {method: :delete, remote: true, class: "heart"} do %>
  <i class="fa fa-heart"></i>
<% end %>
<%= post.likes_count %>

app/views/posts/_post.html.erb
<div>
  <p>【メールアドレス】 <%= post.user.email %></p>
  <p>【内容】 <%= post.content %></p>
  <p>
    <%= link_to "詳細", post %>
    <%= link_to "編集", edit_post_path(post) %>
    <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
</div>
<hr>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">編集</h1>
  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class="search-form">
  <h1 class="text-center">スタジオを探す</h1>
  <%= search_form_for @q, url: posts_path do |f| %>
    <div class="form-group">
      <%= f.search_field :name_cont, class:"form-control", type:"search", placeholder:"店舗名" %>
    </div>
    <div class="form-group">
      <%= f.collection_select :ward_id_eq, Ward.all, :id, :name, {include_blank: "エリア"}, class: "form-control" %>
    </div>
    <div class=form-group>
      <%= f.search_field :address_cont, autofocus: true, class: "form-control", type:"search", placeholder:"住所" %>
    </div>
    <div class="search-button">
      <%= f.submit "検索", class: "btn btn-block" %>
    </div>
  <% end %>
  <h4 class="title text-center mb-4"><%= @count %>件の検索結果</h4>
  <div class="row posts-group">
    <% @posts.each do |post| %>
      <div class="col-14 col-md-6 col-lg-4 text-card-container">
        <%= link_to post, class: "card content-card text-decoration-none" do %>
          <div class="card-header p-0">
            <%= image_tag post.img.url, class: "card-img-top" %>
          </div>
          <div class="card-body text-dark text-card-body">
            <p class="card-text text-title"><%= post.name %></p>
            <p class="post-address"><%= post.ward.name %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
</div>
<%= paginate @posts %>
<h1>投稿一覧</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="text-center">店舗登録</h2>
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="contents-title text-center mt-3 mb-3">
  <h2 class="main-title"><%= @post.name %></h2>
</div>
<section class="container mb-3">
  <div class="row p-0 d-flex mb-2 justify-content-center">
    <div class="col-sm-10 col-md-10 col-lg-6 order-lg-1">
      <div class="thumbnail">
        <% if @post.img? then %>
          <%= image_tag @post.img.url ,class: 'full_image' %>
        <% end %>
      </div>
      <p class="link-box">
        <span class="post-date pull-right mt-3">
          <i class='fas fa-clock home-icon'></i> <%= time_ago_in_words(@post.created_at) %>前
        </span>
        <% if current_user.id == @post.user_id %>
          <%= link_to edit_post_path(@post), method: :get do %>
            <i class="fas fa-pen"></i> (編集)
          <% end %>
          <%= link_to post_path(@post), method: :delete,data: { confirm: "削除しますか？", remote: true } do %>
            <i class="far fa-trash-alt"></i> (削除)
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="card-post col-md-12 col-lg-6 order-lg-2">
      <div class="col-sm-pu-10 col-md-10 col-lg-10 pt-4 order-lg-2">
        <div class="post">
          <span class="title-label">
            住所
          </span>
          <p class="address">
            <%= @post.address %>
          </p>
        </div>
        <div class="post">
          <span class="title-label">
            公式サイト
          </span>
          <p class="post-url">
            <% if @post.URL? %>
              <%= text_url_to_link(h(@post.URL)).html_safe %>
            <% end%>
          </p>
        </div>
        <div class="post">
          <span class="title-label">
            TEL
          </span>
          <p class="post-tel">
            <% if @post.TEL? %>
              <%= @post.TEL %>
            <% end %>
          </p>
        </div>
        <div class="post">
          <span class="title-label">
            投稿者コメント
          </span>
          <p class="post-content">
            <%= @post.content %>
          </p>
        </div>
        <div class="post-like">
          <p class="link-box m-3">
            <% if user_signed_in? %>
              <p id="post-<%= @post.id %>">
                <% if @post.liked_by?(current_user) %>
                  <%= render "like", post: @post %>
                <% else %>
                  <%= render "dislike", post: @post %>
                <% end %>
              </p>
            <% end %>
          </p>
          <% if user_signed_in? %>
            <h4>コメントする</h4>
            <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
          <% end %>
          <hr>
          <h4>コメント一覧</h4>
          <p>
            <%= render partial: 'comments/index', locals: { comments: @comments } %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class=login-button>
    <%= link_to "トップページへ", root_path, class:"btn btn-block" %>
  </div>
</section>
</div>

app/views/user/_show-post.html.erb
<div class="wrap">
  <div class="row">
    <div class="col-md-6 text-center">
      <% if @user.img? %>
        <%= image_tag @user.img.url, class: "icon-img" %>
      <% else %>
        <%= image_tag "default.png", class: "icon-img" %>
      <% end %>
    </div>
    <div class="col-md-6 text-center">
      <div class="user-name"><%= @user.name %>
        <% if current_user.id == @user.id %>
          <%= link_to edit_user_registration_path(@user.id) do %>
            <span class="fas fa-pen edit-user-btn"></span>
          <% end %>
        <% end %>
      </div>
      <hr class="style-1">
      <h6 class="user-introduction"><%= @user.introduction %></h6>
    </div>
  </div>
  <div class="container">
    <div class="col-mb-3">
      <h1 class="user-post mt-4">登録したスタジオ</h1>
      <hr class="style-1">
      <% if @posts.present? %>
        <%= render partial: "user-post", collection: @posts, as: :post %>
      <% else %>
        <h3 class="user-post">まだ登録がありません</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user-post.html.erb
<div class="card-user col-mb-3">
  <h4 class="card-title mt-3"><a href="/posts/<%= post.id %>"><%= post.name %></a></h4>
  <div class="user-card-body">
    <p class="user-post-address"><%= post.address %></p>
    <p class="user-post-date"><%= post.created_at.strftime('%Y/%m/%d') %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrap">
  <div class="row">
    <div class="col-md-6 text-center">
      <% if @user.img? %>
        <%= image_tag @user.img.url, class: "icon-img" %>
      <% else %>
        <%= image_tag "default.png", class: "icon-img" %>
      <% end %>
    </div>
    <div class="col-md-6 text-center">
      <div class="user-name"><%= @user.name %> <%= @user.gender_i18n %></i>
      <% if current_user.id == @user.id %>
        <%= link_to edit_user_registration_path(@user.id) do %>
          <span class="fas fa-pen edit-user-btn"></span>
        <% end %>
      <% end %>
    </div>
    <hr class="style-1">
    <h6 class="user-introduction"><%= @user.introduction %></h6>
  </div>
</div>
<div class="container">
  <div class="col-mb-3">
    <h1 class="user-post mt-4">登録したスタジオ</h1>
    <hr class="style-1">
    <% if @posts.present? %>
      <%= render partial: "user-post", collection: @posts, as: :post %>
    <% else %>
      <h3 class="user-post">まだ登録がありません</h3>
    <% end %>
  </div>
</div>
</div>